[package]
name = "IPPD"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
ocl = "0.19.7"
punkt = "1.0.5"
rayon = "1.10.0"
regex = "1.11.1"
rust_readability = "0.2.0"
serde = "1.0.219"
stop-words = "0.8.1"
